name: Release new version

on:
  release:
    types: [published]

env:
  ONTOLOGY_NAME: pink_annotation_schema
  TAG: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  release_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create and copy generated files to versions/
        run: |
          mkdir -p versions/${TAG#v}
          cp -rf \
              README.md \
              keywords.md \
              ${ONTOLOGY_NAME}.ttl \
              ${ONTOLOGY_NAME}-inferred.ttl \
              docs/ \
              versions/${TAG#v}/.

      - name: Push to gh-pages
        run: |
          git config --global user.email "${ONTOLOGY_NAME}@pink.eu"
          git config --global user.name "${ONTOLOGY_NAME}"
          git add versions/${TAG#v}
          git commit -m "Release version ${TAG#v}"
          git push origin gh-pages
